### ISSUE TITLE
Docker run it not working

### ISSUE THREAD

**Issue by haichuanyu** [gopherdata/gophernotes#137]
$ docker run -it -p 8888:8888 gopherdata/gophernotes
Unable to find image 'gopherdata/gophernotes:latest' locally
latest: Pulling from gopherdata/gophernotes
f4900964ff56: Pull complete 
6733b05fd79a: Pull complete 
27592be9fe6d: Pull complete 
Digest: sha256:021a0a12537d6b00714898dc0c308112b83a672fb527171ddd66cad6f75bf2f7
Status: Downloaded newer image for gopherdata/gophernotes:latest
Traceback (most recent call last):
  File "/usr/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 47, in <module>
    ioloop.install()
  File "/usr/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

**Comment by AlexanderJLiu** [comment]
The same error occured both for latest and latest-ds version
