### ISSUE TITLE
On Ubuntu 14 - error gophernotes: command not found

### ISSUE THREAD

**Issue by ArthurZ** [gopherdata/gophernotes#143]
On Ubuntu 14, using Go 1.11 - error when testing gophernotes: `command not found`
And in Jupyter Notebook a Kernel error:
```
Traceback (most recent call last):
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/home/arthur/anaconda/lib/python2.7/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/home/arthur/anaconda/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/arthur/anaconda/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by LB-Yu** [comment]
Hi!
I got the same problem. Did you solve it?

**Comment by cosmos72** [comment]
Hi,

gophernotes is usually installed in $HOME/go/bin

Did you add that directory to the environment variable $PATH ?

**Comment by LB-Yu** [comment]
Thanks mate!
