### ISSUE TITLE
Dockerize crashes for scipipe code example

### ISSUE THREAD

**Issue by samuell** [gopherdata/gophernotes#23]
I haven't really digged much into this yet, but though I should start with reporting that the dockerize command does not work for my [scipipe example](https://github.com/samuell/scipipe/blob/master/examples/ex13jupyternotebook/ex13jupyternotebook.ipynb).

I'm getting this output in the terminal:

``` bash
[samuel ex13jupyternotebook]$ jupyter notebook ex13jupyternotebook.ipynb 
[I 10:07:44.211 NotebookApp] Serving notebooks from local directory: /home/samuel/code/go/src/github.com/samuell/scipipe/examples/ex13jupyternotebook
[I 10:07:44.212 NotebookApp] 0 active kernels 
[I 10:07:44.212 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 10:07:44.212 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
[I 10:07:46.470 NotebookApp] Kernel started: 2fe8c997-b1f6-49d7-9cc1-fad18e60971e
[I 10:07:46.560 NotebookApp] Adapting to protocol v4.0 for kernel 2fe8c997-b1f6-49d7-9cc1-fad18e60971e
Dockerizing
exit status 1
panic: exit status 1

goroutine 1 [running]:
github.com/gophergala2016/gophernotes/replpkg.actionContainerize(0xc8200aa160, 0x0, 0x0, 0x0, 0x0)
    /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/replpkg/commands.go:358 +0x849
github.com/gophergala2016/gophernotes/replpkg.(*Session).Eval(0xc8200aa160, 0xc8202386f0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/replpkg/repl.go:315 +0x12c5
main.HandleExecuteRequest(0xc82022ee00, 0x20, 0xc8202385d0, 0x8, 0xc82022ee20, 0x20, 0xc8202385e0, 0xf, 0x0, 0x0, ...)
    /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/execution.go:57 +0x30d
main.HandleShellMsg(0xc82022ee00, 0x20, 0xc8202385d0, 0x8, 0xc82022ee20, 0x20, 0xc8202385e0, 0xf, 0x0, 0x0, ...)
    /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/gophernotes.go:71 +0x9a
main.RunKernel(0x7ffec8299b3c, 0x47, 0x7f8855d5a1c0, 0xc82000e3c0)
    /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/gophernotes.go:157 +0x971
main.main()
    /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/main.go:25 +0x246

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /home/samuel/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, locked to thread]:
github.com/gophergala2016/gophernotes/Godeps/_workspace/src/github.com/alecthomas/gozmq._C2func_zmq_device(0x2, 0x2606a50, 0x2606a50, 0x0, 0x0, 0x0)
    ??:0 +0x4d
github.com/gophergala2016/gophernotes/Godeps/_workspace/src/github.com/alecthomas/gozmq.Device(0x2, 0xc82022d9e0, 0xc82022d9e0, 0x0, 0x0)
    /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/Godeps/_workspace/src/github.com/alecthomas/gozmq/zmq.go:442 +0x57
created by main.PrepareSockets
    /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/gophernotes.go:60 +0x8bb
[I 10:07:52.469 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 2fe8c997-b1f6-49d7-9cc1-fad18e60971e restarted
```

System info:
OS: Xubuntu 14.04 LTS 64bit
Go version: go1.5 linux/amd64
Python version: 2.7.10

**Comment by samuell** [comment]
Same with Go 1.6.2 (don't know why I didn't have it installed):

```bash
[samuel ex13jupyternotebook]$ jupyter notebook ex13jupyternotebook.ipynb 
[I 14:48:46.815 NotebookApp] Serving notebooks from local directory: /home/samuel/code/go/src/github.com/samuell/scipipe/examples/ex13jupyternotebook
[I 14:48:46.815 NotebookApp] 0 active kernels 
[I 14:48:46.815 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 14:48:46.815 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
[I 14:48:49.253 NotebookApp] Kernel started: 260f47cb-c79d-40bb-920b-c04a2e367cbb
[I 14:48:49.333 NotebookApp] Adapting to protocol v4.0 for kernel 260f47cb-c79d-40bb-920b-c04a2e367cbb
Dockerizing
exit status 1
panic: exit status 1

goroutine 1 [running]:
github.com/gophergala2016/gophernotes/replpkg.actionContainerize(0xc8200aa160, 0x0, 0x0, 0x0, 0x0)
        /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/replpkg/commands.go:358 +0x849
github.com/gophergala2016/gophernotes/replpkg.(*Session).Eval(0xc8200aa160, 0xc8204666f0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/replpkg/repl.go:315 +0x12c5
main.HandleExecuteRequest(0xc8204644a0, 0x20, 0xc8204665d0, 0x8, 0xc8204644c0, 0x20, 0xc8204665e0, 0xf, 0x0, 0x0, ...)
        /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/execution.go:57 +0x30d
main.HandleShellMsg(0xc8204644a0, 0x20, 0xc8204665d0, 0x8, 0xc8204644c0, 0x20, 0xc8204665e0, 0xf, 0x0, 0x0, ...)
        /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/gophernotes.go:71 +0x9a
main.RunKernel(0x7ffee86018bf, 0x47, 0x7f76d394d1c0, 0xc82000e3d0)
        /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/gophernotes.go:157 +0x971
main.main()
        /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/main.go:25 +0x246

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/samuel/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, locked to thread]:
github.com/gophergala2016/gophernotes/Godeps/_workspace/src/github.com/alecthomas/gozmq._C2func_zmq_device(0x2, 0xbf1a50, 0xbf1a50, 0x0, 0x0, 0x0)
        ??:0 +0x4d
github.com/gophergala2016/gophernotes/Godeps/_workspace/src/github.com/alecthomas/gozmq.Device(0x2, 0xc82022f9a0, 0xc82022f9a0, 0x0, 0x0)
        /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/Godeps/_workspace/src/github.com/alecthomas/gozmq/zmq.go:442 +0x57
created by main.PrepareSockets
        /home/samuel/code/go/src/github.com/gophergala2016/gophernotes/gophernotes.go:60 +0x8bb
[I 14:48:58.251 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 260f47cb-c79d-40bb-920b-c04a2e367cbb restarted
```

**Comment by dwhitena** [comment]
Hi @samuell.  Thanks for the detailed info.  What version of Docker are you running?

**Comment by samuell** [comment]
Hi @dwhitena , right now, I have:
```bash
[samuel ex14scattergather]$ sudo docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/amd64
```

**Comment by dwhitena** [comment]
@samuell Looking into this.  Thanks for the info.

**Comment by dwhitena** [comment]
We no longer have support for dockerize in the new v1 RC.  Maybe we will add it back in, but closing this for now.
